name = "air-hex-logo"
main = "src/index.ts"
compatibility_date = "2024-01-29"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "cf-r2"

[triggers]
# this is run every 30 mints
crons = ["*/30 * * * *"] 
# this is run every 1 mint
# crons = [* * * * *]